[build]
  command = 'npm run ci:build'
  publish = 'out'

[template.environment]
  SANITY_STUDIO_API_PROJECT_ID='Sanity Project ID'
  SANITY_STUDIO_API_DATASET='Sanity Dataset Name'

[[redirects]]
  from = "/*"
  to = "/"
  status = 200
